# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stem_type', models.CharField(max_length=30)),
                ('difficulty_degree', models.CharField(max_length=2)),
                ('stem', models.CharField(max_length=3000, verbose_name='stem')),
                ('options', models.CharField(blank=True, max_length=1000)),
                ('answer', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=11)),
                ('password', models.CharField(max_length=64)),
                ('ip', models.CharField(max_length=15)),
                ('score', models.IntegerField()),
            ],
        ),
    ]
